[build]
  publish = "publish"
  command = "bash build.sh"

[functions]
  directory = "publish/api"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
